INSERT INTO fuel (COUNT, FUEL_TYPE) VALUES (5000, 'АИ-92');
INSERT INTO fuel (COUNT, FUEL_TYPE) VALUES (5000, 'АИ-95');
INSERT INTO fuel (COUNT, FUEL_TYPE) VALUES (5000, 'АИ-98');
INSERT INTO fuel (COUNT, FUEL_TYPE) VALUES (5000, 'ДТ');

INSERT INTO auto (BRAND, MODEL, NUM, FUEL_ID) VALUES ('Mers', 'gl500', '1234-IA7', 3);
INSERT INTO auto (BRAND, MODEL, NUM, FUEL_ID) VALUES ('Fiat', 'a100', '4434-IT7', 1);
INSERT INTO auto (BRAND, MODEL, NUM, FUEL_ID) VALUES ('Scania', 'kakw00', '8202-EE6', 4);

INSERT INTO drivers (AUTO_NUM, FATHERS_NAME, FIRST_NAME, LAST_NAME, auto_ID) VALUES ('1234-IA7', 'ssf', 'sadaf', 'sadfa', '1');
INSERT INTO drivers (AUTO_NUM, FATHERS_NAME, FIRST_NAME, LAST_NAME, auto_ID) VALUES ('1234-IA7', '123', 'sadaf', 'sadfa', '1');